Summary: foo
Name: foo
Version: 1
Release: 1
License: GPL
Group: Development/Languages
Source: %{name}-%{version}.tar.gz
%description
dummy RPM to get RPM environment variables (BUILD and SRC)

%prep
%setup -q -n %{name}-%{version}

%build

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/tmp/
install -d -m 755 $RPM_BUILD_ROOT/tmp/

cp -rf %{_topdir}/SOURCES/* $RPM_BUILD_ROOT/tmp/
file=/tmp/rpm_env
[[ -f $file ]] && rm $file
echo '# this file is generated by using rpm -bp rpm_env.spec' >$file
echo RPM_BUILD_DIR=%{_builddir}    >>$file
echo RPM_RPMS_DIR=%{_rpmdir}       >>$file
echo RPM_SOURCES_DIR=%{_sourcedir} >>$file
echo RPM_SPECS_DIR=%{_specdir}     >>$file
echo RPM_SRPMS_DIR=%{_srcrpmdir}   >>$file
echo RPM_DOC_DIR=%{_docdir}        >>$file
echo RPM_TOP_DIR=%{_topdir}        >>$file
echo ARCH=%{_target_cpu}           >>$file
echo PREFIX=%{_prefix}             >>$file
echo TMP=%{_tmppath}               >>$file

%files
%dir /tmp/myproject
/tmp/myproject/hello.txt
